### ISSUE TITLE
Removing the "A preprint" text

### ISSUE THREAD

**Issue by OmarFRobledo** [kourgeorge/arxiv-style#10]
Hi,

I found a bug concerning the removal of the "A preprint" text below the title. There is a command to do so (\headeright), but it doesn't work. I found that in the part of 'arxiv.sty' in which you renew the '\@maketitle' command it's directly referenced 'A preprint' instead of \headeright. Changing that part of the file for the actual command, everything works fine.

By the way, thanks for this lovely template.

Kind regards,
Omar

**Comment by ReallyPuzzle** [comment]
Open arxiv.sty and find the line 224
Comment that line with "%" so that the "A preprint" will disappear in pdf.

**Comment by kourgeorge** [comment]
This issue was resolved by providing an option to control the text under the title similar to what was done in the header.
