### ISSUE TITLE
Alternate citation styles (citep, citep*, citet, citet*) not working

### ISSUE THREAD

**Issue by gokhanercan** [kourgeorge/arxiv-style#12]
Hi, thanks for your contribution. 

I'm trying to achieve (Author et al., 2019) kind of style for citations. I couldn't get it working with \citet or \citep commands even on default tex and sty files. All files are up to date. I'm using overleaf. 

`\subsection{Testing Citation Styles}
An author did that
\cite{kour2014fast}
or that
\citet{kour2014fast}
or that
\citet*{kour2014fast}
or that
\citep*{kour2014real}
or that
\citep{kour2014real}.
`
renders something like

"An author did that [2] or that(author?)[2] or that(author?)[2] or that [1] or that [1] "

Live editable overleaf link: https://www.overleaf.com/6216354956trmmkphqqpbr
(Search for the section Testing Citation Styles)

**Comment by gokhanercan** [comment]
I solved my own problem by converting the bib style from _unsrt_ to _abbrvnat_ and adding natbib package reference as follows: 
`\usepackage[round]{natbib}`
Here is my fork: https://github.com/gokhanercan/arxiv-style

\citep usage stated in the documentation (NIPS) still not working in this repo if I'm not missing something else.

**Comment by da5nsy** [comment]
It might also be worth considering the addition of the `doi` package which automatically makes DOIs into links in the bibliography (and, I understand, deals with the various symbols that turn up in DOIs that otherwise mess up LaTeX).

**Comment by kourgeorge** [comment]
Hi, Thanks for your suggestion.
Please propose a change.

**Comment by gokhanercan** [comment]
Hi @kourgeorge, my solution ended up converting citations to rounded bibliography style (Kour and Saabne, 2014b) **completely** instead of the numbered one [1]. It is a matter of preference I think, so I don't wanna mess this repo's default citation format up. I couldn't find a way to use both usages at the same style template. Please feel free to close the issue. Thank you. 

Ex:  An author did something Kour and Saabne (2014a) or Kour and Saabne (2014a) or Kour and Saabne (2014a) or (Kourand Saabne, 2014b) or (Kour and Saabne, 2014b) 

Here is my fork: https://github.com/gokhanercan/arxiv-style
Demo link: https://www.overleaf.com/read/nvyydpvrhxcv

**Comment by da5nsy** [comment]
I think the comment in the example tex file about natbib suggests that the original vision was that natbib *would* be used, so I'll go ahead and make a pull request that includes natbib (and so allows the use of \citep and \citet), but keeps the square bracket as default.

**Comment by kourgeorge** [comment]
See #21.

**Comment by kourgeorge** [comment]
See #21.
