### ISSUE TITLE
Authors with same institution

### ISSUE THREAD

**Issue by albertotb** [kourgeorge/arxiv-style#13]
Is there any way to list authors that have the same institution? It would be a nice feature to avoid repetition.

**Comment by raevskymichail** [comment]
There is a fork of that project that refers to author affiliation by footnote:
https://github.com/brenhinkeller/preprint-template.tex

**Comment by kourgeorge** [comment]
Hi. for 2 co-authors, the following workaround works. However, I agree that a more general solution should be implemented. I hope I will have time to work on it soon. 

\author{
  David S.~Hippocampus\\
  \texttt{hippo@cs.cranberry-lemon.edu} \\
  %% examples of more authors
   \And
 Elias D.~Striatum \\
  \texttt{stariate@ee.mount-sheikh.edu} \\
     \And
   \\
  Department of Electrical Engineering\\
  Mount-Sheikh University\\
  Santa Narimana, Levand \\
}
