### ISSUE TITLE
two columns

### ISSUE THREAD

**Issue by alexandrupaler** [kourgeorge/arxiv-style#16]
I experimented to format the preprint with `\documentclass[10pt,twocolumn]{article} ` but the second column flows over the title and author list. Can you please help with to support double column style?

**Comment by kourgeorge** [comment]
You can use the following fork https://github.com/brenhinkeller/preprint-template.tex for a 2 column style.

**Comment by bradknox** [comment]
Unfortunately, that fork is now a very different style than this NeurIPS-inspired style, one that to my eye doesn't look like a computer science paper. I also would find twocolumn support helpful for this arxiv.sty file. 

Either way, thanks for making this style file available!

**Comment by bradknox** [comment]
For others who are interested, the following changes are not ideal but did get me to an acceptable two-column format.

In arxiv.sty, just before `\endinput`, change the latex around `\renewenvironment{abstract}` to the following.
```
\usepackage{changepage}
% abstract styling
\renewenvironment{abstract}
{
  \centerline
  {\large \bfseries \scshape Abstract}
  % \begin{quote}
  \begin{adjustwidth}{5mm}{5mm}  % Adjust the numbers
}
{
  % \end{quote}
  \end{adjustwidth}
}
```

In your main .tex file, change `\documentclass{article}` to `\documentclass[twocolumn]{article}`.

Here's the ugly hack part. Right before the text that starts the right column, add 
```
\newpage
~
\vspace{76mm}
```

You might need to adjust the vspace. Also, I was lucky to have the abstract take up the full left column, providing a clean start for the right column. If the column starts in the middle of a paragraph, you'll presumably need to split that paragraph---maybe mid-sentence or even mid-word---to allow inserting the newpage and vspace.
