### ISSUE TITLE
Missing \begin{document}

### ISSUE THREAD

**Issue by adimanuwal** [kourgeorge/arxiv-style#4]
After following your method, i am getting an error of 'Missing \begin{document}'. I dont know why.
Here's the complete error:-

TeX log appears below
[verbose]: Creating arXiv submission AutoTeX object
[verbose]: *** Using TeX Live 2016 ***
[verbose]: Calling arXiv submission AutoTeX process
[verbose]: TeX/AutoTeX.pm: admin_timeout = minion
[verbose]: <rxjsinav.pdf> is of type 'PDF'.
[verbose]: <whivsnhidan.pdf> is of type 'PDF'.
[verbose]: <rxjc1lowcloudy.pdf> is of type 'PDF'.
[verbose]: <pggals_1.pdf> is of type 'PDF'.
[verbose]: <virgogals.pdf> is of type 'PDF'.
[verbose]: <mnras.bst> is of type 'TeX auxiliary'.
[verbose]: <bhidist.pdf> is of type 'PDF'.
[verbose]: <uptwogals.pdf> is of type 'PDF'.
[verbose]: <sbsgals.pdf> is of type 'PDF'.
[verbose]: <mnras.cls> is of type 'TeX auxiliary'.
[verbose]: <sbscnav.pdf> is of type 'PDF'.
[verbose]: <CIV-group_final.tex> is of type 'PDFLATEX'.
[verbose]: <arxiv.sty> is of type 'TeX auxiliary'.
[verbose]: <sbshighcloudy1.pdf> is of type 'PDF'.
[verbose]: <rxjgals.pdf> is of type 'PDF'.
[verbose]: <rxjlinesfree.pdf> is of type 'PDF'.
[verbose]: <rxjc1highcloudy.pdf> is of type 'PDF'.
[verbose]: <rxjcnav.pdf> is of type 'PDF'.
[verbose]: <pglinesfree.pdf> is of type 'PDF'.
[verbose]: <sbssinav.pdf> is of type 'PDF'.
[verbose]: <sbslinesfree.pdf> is of type 'PDF'.
[verbose]: <rxjc2lowcloudy.pdf> is of type 'PDF'.
[verbose]: <sbslowcloudy2.pdf> is of type 'PDF'.
[verbose]: <pg1148highcloudy2.pdf> is of type 'PDF'.
[verbose]: <pgcnav.pdf> is of type 'PDF'.
[verbose]: <pg1148lowcloudy2.pdf> is of type 'PDF'.
[verbose]: <rxjc2highcloudy.pdf> is of type 'PDF'.
[verbose]: ~~~~~~~~~~~ Processing file 'CIV-group_final.tex'
[verbose]: arXiv Warning: user included plain hyperref directive.
[verbose]: arXiv Warning: user included plain hyperref directive.
[verbose]: TEXMFCNF is unset.
[verbose]: ~~~~~~~~~~~ Running hpdflatex for the first time ~~~~~~~~
[verbose]: Running: "(export HOME=/tmp PATH=/texlive/2016/bin/arch:/bin; cd /submissions/2539304/ && pdflatex 'CIV-group_final.tex' < /dev/null)" 2>&1
[verbose]: This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
restricted \write18 enabled.
entering extended mode
(./CIV-group_final.tex
LaTeX2e <2016/03/31> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(/texlive/2016/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/texlive/2016/texmf-dist/tex/latex/base/size10.clo)) (./arxiv.sty
(/texlive/2016/texmf-dist/tex/latex/geometry/geometry.sty
(/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/texlive/2016/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/texlive/2016/texmf-config/tex/latex/latexconfig/geometry.cfg))
(/texlive/2016/texmf-arxiv/tex/latex/fancyhdr/fancyhdr.sty))
(/texlive/2016/texmf-dist/tex/latex/base/inputenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/utf8.def
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.dfu)
(/texlive/2016/texmf-dist/tex/latex/base/ot1enc.dfu)
(/texlive/2016/texmf-dist/tex/latex/base/omsenc.dfu)))
(/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.def))
(/texlive/2016/texmf-dist/tex/latex/hyperref/hyperref.sty
(/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/texlive/2016/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/texlive/2016/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/texlive/2016/texmf-config/tex/latex/latexconfig/hyperref.cfg)
(/texlive/2016/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver: hpdftex.

(/texlive/2016/texmf-dist/tex/latex/hyperref/hpdftex.def
(/texlive/2016/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/texlive/2016/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/texlive/2016/texmf-dist/tex/latex/amsfonts/amsfonts.sty)
(/texlive/2016/texmf-dist/tex/latex/units/nicefrac.sty
(/texlive/2016/texmf-dist/tex/latex/base/ifthen.sty))
(/texlive/2016/texmf-dist/tex/latex/microtype/microtype.sty
(/texlive/2016/texmf-dist/tex/latex/microtype/microtype-pdftex.def)
(/texlive/2016/texmf-dist/tex/latex/microtype/microtype.cfg))
(/texlive/2016/texmf-dist/tex/latex/lipsum/lipsum.sty)
(/texlive/2016/texmf-dist/tex/latex/newtx/newtxtext.sty
`newtxtext' v1.5, 2016/08/12 Text macros taking advantage of TeX-Gyre Termes fo
nts (msharpe) (/texlive/2016/texmf-dist/tex/latex/fontaxes/fontaxes.sty)
(/texlive/2016/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/texlive/2016/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/texlive/2016/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/texlive/2016/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.def))
(/texlive/2016/texmf-dist/tex/latex/base/textcomp.sty
(/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def
(/texlive/2016/texmf-dist/tex/latex/base/ts1enc.dfu)))
Babel
(/texlive/2016/texmf-dist/tex/latex/newtx/t1ntxtlf.fd))
(/texlive/2016/texmf-dist/tex/latex/newtx/newtxmath.sty
`newtxmath' v1.514, 2016/11/18 Math macros based on txfonts (msharpe)
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/texlive/2016/texmf-dist/tex/latex/amsmath/amstext.sty
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/texlive/2016/texmf-dist/tex/generic/kastrup/binhex.tex))
(/texlive/2016/texmf-dist/tex/latex/ae/ae.sty
(/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.def)
(/texlive/2016/texmf-dist/tex/latex/ae/t1aer.fd)))
(/texlive/2016/texmf-dist/tex/latex/ae/aecompl.sty)
(/texlive/2016/texmf-dist/tex/latex/tools/bm.sty)
(/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/texlive/2016/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/texlive/2016/texmf-dist/tex/latex/amsfonts/amssymb.sty)
(/texlive/2016/texmf-dist/tex/latex/threeparttable/threeparttable.sty)

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...

l.144 \title[C
ool gas in galaxy groups/clusters]{C IV absorbers tracing cool...

?
! Emergency stop.
...

l.144 \title[C
ool gas in galaxy groups/clusters]{C IV absorbers tracing cool...

! ==> Fatal error occurred, no output PDF file produced!
Transcript written on CIV-group_final.log.

[verbose]: pdflatex 'CIV-group_final.tex' failed.
[verbose]: TEXMFCNF is unset.
[verbose]: ~~~~~~~~~~~ Running pdflatex for the first time ~~~~~~~~
[verbose]: Running: "(export HOME=/tmp PATH=/texlive/2016/bin/arch:/bin; cd /submissions/2539304/ && pdflatex 'CIV-group_final.tex' < /dev/null)" 2>&1
[verbose]: This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
restricted \write18 enabled.
entering extended mode
(./CIV-group_final.tex
LaTeX2e <2016/03/31> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(/texlive/2016/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/texlive/2016/texmf-dist/tex/latex/base/size10.clo)) (./arxiv.sty
(/texlive/2016/texmf-dist/tex/latex/geometry/geometry.sty
(/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/texlive/2016/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/texlive/2016/texmf-config/tex/latex/latexconfig/geometry.cfg))
(/texlive/2016/texmf-arxiv/tex/latex/fancyhdr/fancyhdr.sty))
(/texlive/2016/texmf-dist/tex/latex/base/inputenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/utf8.def
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.dfu)
(/texlive/2016/texmf-dist/tex/latex/base/ot1enc.dfu)
(/texlive/2016/texmf-dist/tex/latex/base/omsenc.dfu)))
(/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.def))
(/texlive/2016/texmf-dist/tex/latex/hyperref/hyperref.sty
(/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/texlive/2016/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/texlive/2016/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/texlive/2016/texmf-config/tex/latex/latexconfig/hyperref.cfg)
(/texlive/2016/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/texlive/2016/texmf-dist/tex/latex/hyperref/hpdftex.def
(/texlive/2016/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/texlive/2016/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/texlive/2016/texmf-dist/tex/latex/amsfonts/amsfonts.sty)
(/texlive/2016/texmf-dist/tex/latex/units/nicefrac.sty
(/texlive/2016/texmf-dist/tex/latex/base/ifthen.sty))
(/texlive/2016/texmf-dist/tex/latex/microtype/microtype.sty
(/texlive/2016/texmf-dist/tex/latex/microtype/microtype-pdftex.def)
(/texlive/2016/texmf-dist/tex/latex/microtype/microtype.cfg))
(/texlive/2016/texmf-dist/tex/latex/lipsum/lipsum.sty)
(/texlive/2016/texmf-dist/tex/latex/newtx/newtxtext.sty
`newtxtext' v1.5, 2016/08/12 Text macros taking advantage of TeX-Gyre Termes fo
nts (msharpe) (/texlive/2016/texmf-dist/tex/latex/fontaxes/fontaxes.sty)
(/texlive/2016/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/texlive/2016/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/texlive/2016/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/texlive/2016/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.def))
(/texlive/2016/texmf-dist/tex/latex/base/textcomp.sty
(/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def
(/texlive/2016/texmf-dist/tex/latex/base/ts1enc.dfu)))
Babel
(/texlive/2016/texmf-dist/tex/latex/newtx/t1ntxtlf.fd))
(/texlive/2016/texmf-dist/tex/latex/newtx/newtxmath.sty
`newtxmath' v1.514, 2016/11/18 Math macros based on txfonts (msharpe)
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/texlive/2016/texmf-dist/tex/latex/amsmath/amstext.sty
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/texlive/2016/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/texlive/2016/texmf-dist/tex/generic/kastrup/binhex.tex))
(/texlive/2016/texmf-dist/tex/latex/ae/ae.sty
(/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/texlive/2016/texmf-dist/tex/latex/base/t1enc.def)
(/texlive/2016/texmf-dist/tex/latex/ae/t1aer.fd)))
(/texlive/2016/texmf-dist/tex/latex/ae/aecompl.sty)
(/texlive/2016/texmf-dist/tex/latex/tools/bm.sty)
(/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/texlive/2016/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/texlive/2016/texmf-dist/tex/latex/amsfonts/amssymb.sty)
(/texlive/2016/texmf-dist/tex/latex/threeparttable/threeparttable.sty)

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...

l.142 \title[C
ool gas in galaxy groups/clusters]{C IV absorbers tracing cool...

?
! Emergency stop.
...

l.142 \title[C
ool gas in galaxy groups/clusters]{C IV absorbers tracing cool...

! ==> Fatal error occurred, no output PDF file produced!
Transcript written on CIV-group_final.log.

[verbose]: pdflatex 'CIV-group_final.tex' failed.
[verbose]: 'htex' is not a valid TeX format; will ignore.
[verbose]: TEXMFCNF is unset.
[verbose]: ~~~~~~~~~~~ Running htex for the first time ~~~~~~~~
[verbose]: Running: "(export HOME=/tmp PATH=/texlive/2016/bin/arch:/bin; cd /submissions/2539304/ && tex 'CIV-group_final.tex' < /dev/null)" 2>&1
[verbose]: This is TeX, Version 3.14159265 (TeX Live 2016) (preloaded format=tex)
(./CIV-group_final.tex
! Undefined control sequence.
l.1 \documentclass
{article}
?
! Emergency stop.
l.1 \documentclass
{article}
No pages of output.
Transcript written on CIV-group_final.log.

[verbose]: tex 'CIV-group_final.tex' failed.
[verbose]: TEXMFCNF is unset.
[verbose]: ~~~~~~~~~~~ Running tex for the first time ~~~~~~~~
[verbose]: Running: "(export HOME=/tmp PATH=/texlive/2016/bin/arch:/bin; cd /submissions/2539304/ && tex 'CIV-group_final.tex' < /dev/null)" 2>&1
[verbose]: This is TeX, Version 3.14159265 (TeX Live 2016) (preloaded format=tex)
(./CIV-group_final.tex
! Undefined control sequence.
l.1 \documentclass
{article}
?
! Emergency stop.
l.1 \documentclass
{article}
No pages of output.
Transcript written on CIV-group_final.log.

[verbose]: tex 'CIV-group_final.tex' failed.
[verbose]: We failed utterly to process the TeX file 'CIV-group_final.tex'
[error]: Unable to sucessfully process tex files.
*** AutoTeX ABORTING ***

[verbose]: AutoTeX returned error: Unable to sucessfully process tex files.

[verbose]: $autotex->process failed $@: $?: 0 $!: Inappropriate ioctl for device
[verbose]: Error running AutoTeX process:

**Comment by kourgeorge** [comment]
It looks like you are trying to submit your work to arxiv.org. 
I just tried to submit the template.tex file and the arxiv.sty and it worked with no issues.
Did you mistakenly deleted the \begin{document} command or have imported some package which overrides the style? Are you using the latest version of the style? Are you using the template on overleaf? 
Please provide more information.

**Comment by kourgeorge** [comment]
I am closing the issue. 
If you need further help please contact me.
