### ISSUE TITLE
Layout of 5 authors

### ISSUE THREAD

**Issue by OpenWaygate** [kourgeorge/arxiv-style#5]
```
\author{
  Tomas Mikolov \\
  Google Inc.\\
  Mountain View\\
  \texttt{mikolov@google.com} \\
  %% examples of more authors
  \And
  Ilya Sutskever \\
  Google Inc.\\
  Mountain View\\
  \texttt{ilyasu@google.com} \\
  \And
  Kai Chen \\
  Google Inc.\\
  Mountain View\\
  \texttt{kai@google.com} \\
  \And
  Greg Corrado \\
  Google Inc.\\
  Mountain View\\
  \texttt{gcorrado@google.com} \\
  \And
  Jeffrey Dean \\
  Google Inc.\\
  Mountain View\\
  \texttt{jeff@google.com} \\
}
```
in nips 2018 style, it looks like this, 3 + 2
<img width="453" alt="1" src="https://user-images.githubusercontent.com/27287694/53970941-c3c4ba00-4136-11e9-85d9-8bc41a587f3f.png">

but in this arxiv style, it looks like this, 4 + 1
<img width="463" alt="2" src="https://user-images.githubusercontent.com/27287694/53971004-f1a9fe80-4136-11e9-9ae1-35689a43de02.png">

How to modify the arxiy style so that it looks like 3+2 style?

**Comment by kourgeorge** [comment]
Hi,
The number of authors that fits in a single line depends on the **textwidth** parameter defined in the style file.
Try to decrease it to get the required result but note that it will affect the text width of the entire document.
