### ISSUE TITLE
Is there a command for removing the date?

### ISSUE THREAD

**Issue by emanuelepesce** [kourgeorge/arxiv-style#9]
I would like to remove the date that appears after the authors. I already tried \date{} but it does work. There is a command for this or the only solution is to edit the .sty file?

**Comment by kourgeorge** [comment]
HI Emanuaele,
If you add the \date{} just before the \begin{document} it should work.
In any case, I added a comment in the right location in the last version. 
Please update me if that works for you.

**Comment by emanuelepesce** [comment]
Hey, thanks a lot! It works, I just realised I was using an old version taken from Overleaf. 

No problems with the date in this version, however removing the text "A preprint" doesn't seem to work, even though I uncommented the following line as suggesed by the documentation.

```
% Uncomment to override  the `A preprint' in the header
\renewcommand{\headeright}{}
```

**Comment by kourgeorge** [comment]
Did you update the sty file as well?
